name: Docs
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docs:
    strategy:
      # run tests on all versions, even if one fails
      fail-fast: false
      matrix:
        # add any other Typst versions that your package should support
        typst-version:
          - typst: 0.13
            tytanic: 0.2
            # the docs don't need to build with all versions supported by the package;
            # the latest one is enough
            doc: true

    name: Build docs using Typst ${{ matrix.typst-version.typst }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install just and tytanic
        uses: taiki-e/install-action@v2
        with:
          tool: just

      - name: Setup typst
        id: setup-typst
        uses: typst-community/setup-typst@v4
        with:
          typst-version: ${{ matrix.typst-version.typst }}

      - name: Build docs
        if: ${{ matrix.typst-version.doc }}
        run: just doc
